- name: update u1 server
  hosts: u1
  become: yes


  tasks:
  - name: update apt
    apt:
      update_cache: yes

  - name: install apache
    package:
      name: apache2
      state: present

  - name: start apache2
    service:
       name: apache2
       state: started

  - name: enable apache2
    service:
      name: apache2
      enabled: yes
