- name: update all servers
  hosts: all
  become: yes

  tasks:
  - name: Modify SE-linux
    selinux:
      policy: targeted 
      state: permissive

  - name: update config
    copy:
      src: httpd.j2
      dest: /etc/httpd/conf/httpd.conf

  
  - name: restart httpd
    service:
      name: httpd
      state: restarted


